import "@/app/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { roboto } from "../../fonts";
import pick from "lodash/pick";
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  const messages = useMessages();

  return (
    <html lang={locale} className={roboto.className}>
      <body className="flex flex-col w-full min-h-screen">
        <NextIntlClientProvider messages={pick(messages, "Header")}>
          <Header />
        </NextIntlClientProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
