import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { roboto } from "./fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-col w-full min-h-screen">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
